### ISSUE TITLE
Not Replaced Log

### ISSUE THREAD

**Issue by andrewcharnley** [tomaszczechowski/gulp-string-replace#2]
Nice plugin, neatly wraps vinyl streams and works well.

One minor issue, the "Not Replaced" statements are not necessary. The red makes it look like an error.

**Comment by tomaszczechowski** [comment]
Thanks for option :)

I'll take a glance on this "issue/improvement" asap.

**Comment by tomaszczechowski** [comment]
Hey, 

Version 0.2.0 has been released. Please add "options" object along with "notReplace" parameter in order to turn off logs once nothing was replaced. Additionally the "Not replace" statement is not displayed in red color anymore. 

Don't forget to watch and rate project ;)

Have a good weekend. Bye
